package io.artoo.lance.task;

public final class TaskException extends RuntimeException {
  public TaskException(final Throwable cause) {
    super(cause);
  }
}
